In [1]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.cluster import KMeans
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report
from sklearn.metrics import confusion_matrix
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score
import numpy as np
import pandas as pd 
import numpy as np
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import precision_score,recall_score,f1_score
from sklearn.metrics import confusion_matrix
from sklearn.svm import SVC

In [2]:
data = pd.read_csv('final_with_covid_AS.csv')
data.head()

,CountCases,BedDys,BeddystoCC,Severity,DiedCases,DiedBdDys,Hsptlsns,April,August,December,...,Y2013,Y2014,Y2015,Y2016,Y2017,Y2018,Y2019,Y2020,Y2021,CovidPrd
0,17,133,7.823529,75,4,9,13,0,0,0,...,1,0,0,0,0,0,0,0,0,0
1,13,372,28.615385,63,4,34,9,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,8,106,13.250000,48,4,13,4,0,0,0,...,0,0,0,0,0,1,0,0,0,0
3,45,218,4.844444,153,3,24,42,0,0,0,...,0,0,0,1,0,0,0,0,0,0
4,24,238,9.916667,90,3,8,21,0,1,0,...,1,0,0,0,0,0,0,0,0,0

In [3]:
filtered_data = data[data['CarDriver'] == 1]
filtered_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 12582 entries, 11 to 54025
Data columns (total 58 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CountCases       12582 non-null  int64
 1   BedDys           12582 non-null  int64
 2   BeddystoCC       12582 non-null  float64
 3   Severity         12582 non-null  int64
 4   DiedCases        12582 non-null  int64
 5   DiedBdDys        12582 non-null  int64
 6   Hsptlsns         12582 non-null  int64
 7   April            12582 non-null  int64
 8   August           12582 non-null  int64
 9   December         12582 non-null  int64
 10  February         12582 non-null  int64
 11  January          12582 non-null  int64
 12  July             12582 non-null  int64
 13  June             12582 non-null  int64
 14  March            12582 non-null  int64
 15  May              12582 non-null  int64
 16  November         12582 non-null  int64
 17  October          12582 non-null  int64
 18  September        12582 non-null  int64
 19  MajorCities      12582 non-null  int64
 20  Regional         12582 non-null  int64
 21  Female           12582 non-null  int64
 22  Male             12582 non-null  int64
 23  Age07            12582 non-null  int64
 24  Age816           12582 non-null  int64
 25  Age1725          12582 non-null  int64
 26  Age2639          12582 non-null  int64
 27  Age4064          12582 non-null  int64
 28  Age6574          12582 non-null  int64
 29  Age75plus        12582 non-null  int64
 30  CarDriver        12582 non-null  int64
 31  CarPngr          12582 non-null  int64
 32  Mtrcyclist       12582 non-null  int64
 33  PdlCyclist       12582 non-null  int64
 34  Pedestrian       12582 non-null  int64
 35  Cntrprt23WldMV   12582 non-null  int64
 36  CntrprtCrTrkVn   12582 non-null  int64
 37  CntrprtFxdStnry  12582 non-null  int64
 38  CntrprtHvyVhcl   12582 non-null  int64
 39  CntrprtNClsn     12582 non-null  int64
 40  CntrprtNA        12582 non-null  int64
 41  CntrprtOther     12582 non-null  int64
 42  CntrprtNMV       12582 non-null  int64
 43  CntrprtPdlC      12582 non-null  int64
 44  CntrprtPdstAnml  12582 non-null  int64
 45  CntrprtTrn       12582 non-null  int64
 46  Y2011            12582 non-null  int64
 47  Y2012            12582 non-null  int64
 48  Y2013            12582 non-null  int64
 49  Y2014            12582 non-null  int64
 50  Y2015            12582 non-null  int64
 51  Y2016            12582 non-null  int64
 52  Y2017            12582 non-null  int64
 53  Y2018            12582 non-null  int64
 54  Y2019            12582 non-null  int64
 55  Y2020            12582 non-null  int64
 56  Y2021            12582 non-null  int64
 57  CovidPrd         12582 non-null  int64
dtypes: float64(1), int64(57)
memory usage: 5.7 MB

In [4]:
filtered_data.shape

(12582, 58)

In [5]:

filtered_data['Bed_days_category'] = np.where(filtered_data['BeddystoCC'] >= 7, 1, 0)

filtered_data['Bed_days_category'].value_counts()

/var/folders/3l/xh28kn0j7_7d5hh7fgz188940000gn/T/ipykernel_2984/2325546250.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_data['Bed_days_category'] = np.where(filtered_data['BeddystoCC'] >= 7, 1, 0)

0    9688
1    2894
Name: Bed_days_category, dtype: int64

In [6]:
filtered_data.shape

(12582, 59)

In [10]:
from xgboost import XGBClassifier

import xgboost as xgb


X = filtered_data[['Age1725','Age2639','Age4064','Age6574','Age75plus',
                   'Male',
                   'Regional',

                   'April','December','February','January','July',
                   'June','March','May','November','October','September',

                   'Cntrprt23WldMV','CntrprtFxdStnry','CntrprtHvyVhcl',
                   'CntrprtNClsn','CntrprtOther','CntrprtNMV','CntrprtCrTrkVn',
                   'CntrprtPdlC','CntrprtPdstAnml','CntrprtTrn',

                   'Y2014','Y2015','Y2016','Y2017','Y2018','Y2019','Y2020','Y2021',
                   'Y2013','Y2012',
                   'CovidPrd']]



y = filtered_data['Bed_days_category']



X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [11]:
from imblearn.over_sampling import SMOTE, ADASYN

smote = SMOTE(random_state=42)
X_train_smote, y_train_smote = smote.fit_resample(X_train, y_train)

# MODEL

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, ExtraTreesClassifier
from xgboost import XGBClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline
from imblearn.over_sampling import RandomOverSampler

# Ù¾ÛŒØ´ Ø§Ø² ØªÙ‚Ø³ÛŒÙ… Ø¯Ø§Ø¯Ù‡â€ŒÙ‡Ø§ Ø¨Ù‡ Ø¢Ù…ÙˆØ²Ø´ Ùˆ Ø¢Ø²Ù…ÙˆÙ†
#ros = RandomOverSampler(random_state=42)
#X_resampled, y_resampled = ros.fit_resample(X, y)

# Ø³Ù¾Ø³ Ø§Ø¯Ø§Ù…Ù‡ Ú©Ø¯ Ø¨Ø§ Ø¯Ø§Ø¯Ù‡â€ŒÙ‡Ø§ÛŒ Ø¬Ø¯ÛŒØ¯
X_train, X_test, y_train, y_test = train_test_split(X_train_smote, y_train_smote, test_size=0.3, random_state=42)

# Ù…Ø¯Ù„â€ŒÙ‡Ø§ÛŒ Ù¾Ø§ÛŒÙ‡
base_models = [
     XGBClassifier(objective='binary:logistic', random_state=42),
     RandomForestClassifier(random_state=42),
     DecisionTreeClassifier(random_state=42),
     GradientBoostingClassifier(random_state=42),
     KNeighborsClassifier(n_neighbors=5),
     SVC(kernel='linear', probability=True, class_weight='balanced', random_state=42),
     GaussianNB(),
     ExtraTreesClassifier(random_state=42),
     MLPClassifier(hidden_layer_sizes=(64,), random_state=42),
]

# Ø¢Ù…ÙˆØ²Ø´ Ù…Ø¯Ù„â€ŒÙ‡Ø§ÛŒ Ù¾Ø§ÛŒÙ‡
for model in base_models:
    model.fit(X_train, y_train)

# Ø§ÛŒØ¬Ø§Ø¯ ÙˆÛŒÚ˜Ú¯ÛŒâ€ŒÙ‡Ø§ÛŒ Ø¬Ø¯ÛŒØ¯ Ø§Ø² Ø®Ø±ÙˆØ¬ÛŒ Ù…Ø¯Ù„â€ŒÙ‡Ø§ÛŒ Ù¾Ø§ÛŒÙ‡
X_train_meta = [model.predict_proba(X_train) for model in base_models]
X_train_meta = np.concatenate(X_train_meta, axis=1)

X_test_meta = [model.predict_proba(X_test) for model in base_models]
X_test_meta = np.concatenate(X_test_meta, axis=1)

# Ø§ÛŒØ¬Ø§Ø¯ Ùˆ Ø¢Ù…ÙˆØ²Ø´ Ù…Ø¯Ù„ Ù…ØªØ§-Ø·Ø¨Ù‚Ù‡â€ŒØ¨Ù†Ø¯
meta_model = make_pipeline(StandardScaler(), LogisticRegression(random_state=42))
meta_model.fit(X_train_meta, y_train)

# Ø§Ø±Ø²ÛŒØ§Ø¨ÛŒ Ù…Ø¯Ù„
y_pred = meta_model.predict(X_test_meta)
acc = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)
from sklearn.metrics import classification_report

# Ø§Ø±Ø²ÛŒØ§Ø¨ÛŒ Ù…Ø¯Ù„
y_pred = meta_model.predict(X_test_meta)
class_report = classification_report(y_test, y_pred)
f1= f1_score(y_test,y_pred)

print(class_report)
print('Accuracy:', acc)
print('Confusion Matrix:\n', conf_matrix)
print(f1)